schema: 2
game: Path of Exile
version: Leveling Guide
author: exile-leveling (heartofphos) + poe-leveling.com
source: https://heartofphos.github.io/exile-leveling/
chapter: 4
title: 'Act 4: Highgate to Malachai'
next: act5.yaml
sections:
  - title: Highgate to Malachai
    steps:
      - id: 1
        title: Get to Highgate
        description: |-
          - Get to **The Aqueduct**
          - Get to **Highgate**
      - id: 2
        title: Kill Voll, Emperor of Purity
        description: |-
          - Get to **The Dried Lake**
          - Find and kill **Voll, Emperor of Purity**, take *Deshret's Banner*
          - Get Crafting recipe
          - log out
      - id: 3
        title: 'Hand in: Breaking the Seal'
        description: |-
          - Break *Deshret's Seal*
          - Hand in *Breaking the Seal*
      - id: 4
        title: Get to The Mines Level 2
        description: |-
          - Get to **The Mines Level 1**
          - Get Crafting recipe
          - Get to **The Mines Level 2**
          - Free *Deshret*
      - id: 5
        title: 'Hand in: An Indomitable Spirit'
        description: |-
          - Get to **The Crystal Veins**
          - Get Crafting recipe
          - Waypoint to **Highgate**
          - Hand in *An Indomitable Spirit*
      - id: 6
        title: Get to Daresso's Dream
        description: |-
          - Waypoint to **The Sarn Encampment**
          - Get to **Aspirants' Plaza**, get Waypoint
          - Labyrinth (normal)
          - Get Crafting recipe
          - Waypoint to **The Crystal Veins**
          - Get to **Daresso's Dream**
      - id: 7
        title: Get to Kaom's Dream
        description: |-
          - Get to **The Grand Arena**
          - Get Crafting recipe
          - Waypoint to **The Crystal Veins**
          - Get to **Kaom's Dream**
      - id: 8
        title: Kill Daresso, King of Swords
        description: |-
          - Get to **Kaom's Stronghold**
          - Get Crafting recipe
          - Get to **Caldera of the King**, kill **King Kaom**, take *The Eye of Fury*
          - take Portal
          - Waypoint to **The Grand Arena**
          - Get to **The Ring of Blades**, kill **Daresso, King of Swords**, take *The Eye of Desire*
          - log out
        hints:
          - Go up-right to find **Daresso, King of Swords**
          - Follow Bridges to find **Daresso, King of Swords**
          - Go down-left follow the exits keeping left
      - id: 9
        title: Kill Piety, the Abomination
        description: |-
          - Waypoint to **The Crystal Veins**
          - Talk to Lady Dialla
          - Get to **The Belly of the Beast Level 1**
          - Get to **The Belly of the Beast Level 2**
          - Get to **The Bowels of the Beast**, kill **Piety, the Abomination**
          - Talk to Piety
          - Get Crafting recipe
      - id: 10
        title: 'Hand in: Corpus Malachus'
        description: |-
          - Get to **The Harvest**
          - Find and kill **Doedre Darktongue**, take *Malachai's Lungs*
          - Find and kill **Maligaro, The Inquisitor**, take *Malachai's Heart*
          - Find and kill **Shavronne of Umbra**, take *Malachai's Entrails*
          - Hand in *Corpus Malachus*
      - id: 11
        title: Kill Malachai, The Nightmare
        description: |-
          - Get to **The Black Core**, kill **Malachai, The Nightmare**
          - log out
          - Hand in *The Eternal Nightmare*
      - id: 12
        title: Get to The Ascent
        description: |-
          - Get to **The Ascent**
          - Get Crafting recipe
          - Activate *The Resonator*, use *Oriath Portal*
